language: php
 
php:
  - 7.1.3
 
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  
script:
  - find -D tree .

after_script:
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/StackTest.php