language: php
 
php:
  - 7.1.3

before_script: 
 - composer install

script:
  - phpunit --configuration tests/phpunit.xml
  - '! find . -type f -name "*.php" -exec .phpenv/shims/php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'