language: php
 
php:
  - 7.1.3

install:
 - echo "TRAVIS_BUILD_ID : ".$TRAVIS_BUILD_ID
 - curl -s http://getcomposer.org/installer | php
 - php composer.phar install --dev --no-interaction
 - composer require php-coveralls/php-coveralls

script:
 - mkdir -p build/logs
 - phpunit --configuration phpunit.xml

after_success:
 - travis_retry php vendor/bin/php-coveralls -v