language: php
 
php:
  - 7.1.3

before_script: 
 - composer install

script:
  - echo PHP_EOL."script block Before unit test.".PHP_EOL."Present Working Directory : ".PHP_EOL
  - pwd
  - echo PHP_EOL.PHP_EOL
  - phpunit --configuration tests/phpunit.xml
  - echo PHP_EOL."script block After unit test.".PHP_EOL."Present Working Directory : ".PHP_EOL
  - pwd
  - echo PHP_EOL.PHP_EOL

after_script:
 - ls -lahR .