language: php
 
php:
  - 7.1.3
 
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

after_script:
  - ./vendor/phpunit/phpunit/phpunit --bootstrap /vendor/autoload.php tests/StackTest.php