language: php
 
php:
  - 7.1.3
 
#before_script:
#  - wget http://getcomposer.org/composer.phar
#  - php composer.phar install

# Commands you want to run that will verify your build.
#script: phpunit
  
#after_script:
#  - ./vendor/phpunit/phpunit/phpunit --bootstrap vendor/autoload.php tests/StackTest.php

before_script: composer install

script: phpunit --configuration tests/phpunit.xml