language: php
 
php:
  - 7.2.6
 
before_script:
  - wget http://getcomposer.org/composer.phar
  - wget https://phar.phpunit.de/phpunit-7.phar
  - php composer.phar install
  - php phpunit-7.phar install
  - phpunit